/*
 * Copyright (c) 2022 Reva Technology Inc., all rights reserved.
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Licensed under the Elastic License 2.0; you may not use this file except
 * in compliance with the Elastic License 2.0.
 */

export const groupedRegions = [
  {
    name: 'California',
    children: [
      {
        propertyId: '190df0d0-87d6-484f-a4a2-47db904710cd',
        name: 'swparkme',
        displayName: 'Parkmerced Apartments',
        geoLocation: { lat: 37.445099, lng: -122.160362 },
        city: 'San Francisco',
        tags: ['3DTour', 'video'],
        state: 'California',
        region: '',
        address: '700 Lincoln Village Cir',
        cityAliases: ['Oakland', 'San Jose'],
        neighborhood: '',
        stateAliases: ['Cal', 'SF'],
        testimonials: ['Kids have lots of friends at the park around the corner', 'Great staff with lots of organized activities'],
        regionAliases: ['Bay Area'],
        neighborhoodAliases: [],
        childDisplayName: 'San Francisco',
      },
    ],
    id: 'California',
  },
  {
    name: 'New York',
    children: [
      {
        propertyId: '7e8b8cf8-9641-44e6-94c5-39c27b55c328',
        name: 'Sharon',
        displayName: 'Sharon Green',
        geoLocation: { lat: 37.90642, lng: -122.5027 },
        city: 'New York',
        tags: ['3DTour', 'video'],
        state: 'New York',
        region: '',
        address: '700 Lincoln Village Cir',
        cityAliases: ['Oakland', 'San Jose'],
        neighborhood: '',
        stateAliases: ['Cal', 'SF'],
        testimonials: ['Kids have lots of friends at the park around teh corner', 'Great staff with lots of organized activities'],
        regionAliases: ['Bay Area'],
        neighborhoodAliases: [],
        childDisplayName: 'New York',
      },
      {
        propertyId: 'f643c872-0437-4fcc-ba12-7f2af15f1c30',
        name: 'B',
        displayName: 'Creekside Apts',
        geoLocation: { lat: 37.90642, lng: -122.5027 },
        city: 'Queens',
        tags: ['3DTour', 'video'],
        state: 'New York',
        region: '',
        address: '700 Lincoln Village Cir',
        cityAliases: ['Oakland', 'San Jose'],
        neighborhood: '',
        stateAliases: ['Cal', 'SF'],
        testimonials: ['Kids have lots of friends at the park around teh corner', 'Great staff with lots of organized activities'],
        regionAliases: ['Bay Area'],
        neighborhoodAliases: [],
        childDisplayName: 'Queens',
      },
    ],
    id: 'New York',
  },
  {
    name: 'Florida',
    children: [
      {
        propertyId: 'a705ddd7-119b-4993-a53a-d1a7a04582e4',
        name: 'cove',
        displayName: 'The Cove at Tiburon',
        geoLocation: { lat: 37.90642, lng: -122.5027 },
        city: 'Miami',
        tags: ['3DTour', 'video'],
        state: 'Florida',
        region: '',
        address: '700 Lincoln Village Cir',
        cityAliases: ['Oakland', 'San Jose'],
        neighborhood: '',
        stateAliases: ['Cal', 'SF'],
        testimonials: ['Kids have lots of friends at the park around teh corner', 'Great staff with lots of organized activities'],
        regionAliases: ['Bay Area'],
        neighborhoodAliases: [],
        childDisplayName: 'Miami',
      },
    ],
    id: 'Florida',
  },
  {
    name: 'Minnesota',
    children: [
      {
        propertyId: 'fc7e125a-9d56-4529-a5a0-75f27fdaf101',
        name: 'A',
        displayName: 'Pinewood Apts',
        geoLocation: { lat: 37.90642, lng: -122.5027 },
        city: 'Isanti',
        tags: ['3DTour', 'video'],
        state: 'Minnesota',
        region: '',
        address: '700 Lincoln Village Cir',
        cityAliases: ['Oakland', 'San Jose'],
        neighborhood: '',
        stateAliases: ['Cal', 'SF'],
        testimonials: ['Kids have lots of friends at the park around teh corner', 'Great staff with lots of organized activities'],
        regionAliases: ['Bay Area'],
        neighborhoodAliases: [],
        childDisplayName: 'Isanti',
      },
    ],
    id: 'Minnesota',
  },
];
